/* commit to start dev deployment */
import type { Metadata } from "next";
import { Shippori_Mincho_B1 } from "next/font/google";
import "./globals.css";
import Header from "./native-components/Header/Header";
import { PointerWrapper } from "@/components/magicui/pointer";

const shipporiMincho = Shippori_Mincho_B1({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${shipporiMincho.className} antialiased`}>
                <Header />
                {children}
            </body>
        </html>
    );
}
